<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0.U6QFK' shared service.

return $this->privates['.service_locator.0.U6QFK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'company' => array('privates', '.errored..service_locator.0.U6QFK.App\\Entity\\Companies', NULL, 'Cannot autowire service ".service_locator.0.U6QFK": it references class "App\\Entity\\Companies" but no such service exists.'),
));
