<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Jw.V7tv' shared service.

return $this->privates['.service_locator.Jw.V7tv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'employee' => array('privates', '.errored..service_locator.Jw.V7tv.App\\Entity\\Employees', NULL, 'Cannot autowire service ".service_locator.Jw.V7tv": it references class "App\\Entity\\Employees" but no such service exists.'),
));
