<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.0.U6QFK.App\Entity\Companies' shared service.

include_once $this->targetDirs[3].'/src/Entity/Companies.php';

return $this->privates['.errored..service_locator.0.U6QFK.App\Entity\Companies'] = new \App\Entity\Companies();
