<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\CompaniesController::delete' => array('privates', '.service_locator.0.U6QFK', 'get_ServiceLocator_0_U6QFKService.php', true),
    'App\\Controller\\CompaniesController::edit' => array('privates', '.service_locator.0.U6QFK', 'get_ServiceLocator_0_U6QFKService.php', true),
    'App\\Controller\\CompaniesController::show' => array('privates', '.service_locator.0.U6QFK', 'get_ServiceLocator_0_U6QFKService.php', true),
    'App\\Controller\\EmployeesController::delete' => array('privates', '.service_locator.Jw.V7tv', 'get_ServiceLocator_Jw_V7tvService.php', true),
    'App\\Controller\\EmployeesController::edit' => array('privates', '.service_locator.Jw.V7tv', 'get_ServiceLocator_Jw_V7tvService.php', true),
    'App\\Controller\\EmployeesController::show' => array('privates', '.service_locator.Jw.V7tv', 'get_ServiceLocator_Jw_V7tvService.php', true),
    'App\\Controller\\CompaniesController:delete' => array('privates', '.service_locator.0.U6QFK', 'get_ServiceLocator_0_U6QFKService.php', true),
    'App\\Controller\\CompaniesController:edit' => array('privates', '.service_locator.0.U6QFK', 'get_ServiceLocator_0_U6QFKService.php', true),
    'App\\Controller\\CompaniesController:show' => array('privates', '.service_locator.0.U6QFK', 'get_ServiceLocator_0_U6QFKService.php', true),
    'App\\Controller\\EmployeesController:delete' => array('privates', '.service_locator.Jw.V7tv', 'get_ServiceLocator_Jw_V7tvService.php', true),
    'App\\Controller\\EmployeesController:edit' => array('privates', '.service_locator.Jw.V7tv', 'get_ServiceLocator_Jw_V7tvService.php', true),
    'App\\Controller\\EmployeesController:show' => array('privates', '.service_locator.Jw.V7tv', 'get_ServiceLocator_Jw_V7tvService.php', true),
))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
