<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHYll2XG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHYll2XG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHYll2XG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHYll2XG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHYll2XG\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'HYll2XG',
    'container.build_id' => '520d4e10',
    'container.build_time' => 1544056080,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHYll2XG');
