<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHIrcOP7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHIrcOP7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHIrcOP7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHIrcOP7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHIrcOP7\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'HIrcOP7',
    'container.build_id' => '33553e5f',
    'container.build_time' => 1544449983,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHIrcOP7');
